# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='account_logo',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_title',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.AddField(
            model_name='album',
            name='account_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='--choose--', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='password',
            field=models.CharField(default='pass', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='username',
            field=models.EmailField(default='username', max_length=15),
        ),
    ]
