# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20160602_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
    ]
