# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_song_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='account_type',
            field=models.CharField(choices=[('SKYPE', 'SKYPE'), ('FACEBOOK', 'FACEBOOK'), ('GMAIL', 'GMAIL')], default='--choose--', max_length=250),
        ),
    ]
